In [1]:
import numpy as np

In [2]:
myarr=np.zeros(5)

In [3]:
myarr

array([0., 0., 0., 0., 0.])

In [4]:
myarr*5

array([0., 0., 0., 0., 0.])

In [5]:
myarr=np.zeros(5)*5

In [6]:
myarr

array([0., 0., 0., 0., 0.])

In [9]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [10]:
myarray=np.ones(4)
myarray

array([1., 1., 1., 1.])

In [11]:
arr=np.ones(5)*6
arr

array([6., 6., 6., 6., 6.])

In [12]:
myar=np.ones((2,3))
myar

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arra=np.eye(3)

In [14]:
arra

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
arra=np.eye(3,4)
arra

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [16]:
diagonal=np.diag([2,4,6,8])
diagonal

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [17]:
np.diag(diagonal)

array([2, 4, 6, 8])

In [19]:
import numpy as np 
random1=np.random.randint(1,10,6)  #( min,max,total value )
random1

array([7, 9, 3, 6, 1, 9])

In [20]:
import numpy as np 
rand1=np.random.rand(4)     #btw 0 to 1 random number generate.
rand1

array([0.11550691, 0.6806623 , 0.07801383, 0.11115222])

In [21]:
arr=np.random.rand(2,3)
arr

array([[0.10239287, 0.12808246, 0.34918003],
       [0.10391769, 0.95383132, 0.47222524]])

In [22]:
centerz=np.random.randn(7)    #generate number 0 ke center mein. 
centerz

array([-0.08385208, -2.46056721, -0.31363682,  0.26870145, -0.69096401,
       -0.91823493,  0.99096395])

In [26]:
import numpy as np
a=[]
size=int(input("How many Number in array"))
for i in range(size):
  val=int(input("Enter number="))
  a.append(val)
arr=np.array(a)
arr
#for i in range(arr.size):
    #print(arr[i])

How many Number in array5
Enter number=5
Enter number=6
Enter number=7
Enter number=8
Enter number=9


array([5, 6, 7, 8, 9])

In [27]:
push="""
        I am determined, coorperative and punchual person.
        Pursuing bachalor of technology computer science and engineering.
        
        Passionate about programming,AI and ML. I like to explore new things and focus on learning.

"""
push

'\n        I am determined, coorperative and punchual person.\n        Pursuing bachalor of technology computer science and engineering.\n        \n        Passionate about programming,AI and ML. I like to explore new things and focus on learning.\n\n'

In [31]:
import numpy as np
rand2=np.random.randint(1,60,12)
rand2

array([37, 12, 28, 17, 24,  1, 48, 57, 20, 36, 11, 40])

In [32]:
arr=rand2.reshape(3,4)
arr

array([[37, 12, 28, 17],
       [24,  1, 48, 57],
       [20, 36, 11, 40]])

In [33]:
arr=rand2.reshape(2,6)
arr

array([[37, 12, 28, 17, 24,  1],
       [48, 57, 20, 36, 11, 40]])

In [34]:
arr=rand2.reshape(4,-1)  #auto select according to require
arr

array([[37, 12, 28],
       [17, 24,  1],
       [48, 57, 20],
       [36, 11, 40]])

In [10]:
import numpy as np 
np.random.seed(1)
arr=np.random.randint(1,100,10)
arr

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

In [11]:
arr.size

10

In [12]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
b=a[ :2,1:3]
b

array([[2, 3],
       [5, 6]])

In [18]:
a=np.random.seed(111)
a=np.random.randint(1,500,30).reshape(10,3)
a

array([[341, 365, 469],
       [213,  87, 276],
       [170, 323, 119],
       [467, 297, 456],
       [442,   8, 269],
       [267, 450, 369],
       [217, 285, 271],
       [419,  22,  55],
       [201,  38, 461],
       [231, 187, 269]])

In [25]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
slicing=a[3:6]
slicing[:]=7          #7 ke sthan per koi bhi integer value kar sakte hai.
a

array([10, 20, 30,  7,  7,  7, 70, 80])

In [24]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
slicing=a[3:6].copy()
slicing[:]=7
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [27]:
p=np.array([range(16)])
p                              #conditional selection numpy start example

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [28]:
b=p<10
b

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False, False, False, False, False, False]])

In [29]:
c=arr>10
arr[c]

array([38, 13, 73, 76, 80, 65, 17])

In [30]:
import numpy as np 
arr=np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
arr>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [33]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [37]:
best=np.arange(1,15)
best[best%2==0] = 0
best

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0])

In [47]:
import numpy as np 
opr1=np.arange(1,6)             #array operations
opr2=np.arange(7,12)
opr1
opr2

array([ 7,  8,  9, 10, 11])

In [48]:
opr1+opr2

array([ 8, 10, 12, 14, 16])

In [49]:
arr=np.arange(1,5)
arr

array([1, 2, 3, 4])

In [50]:
arr+3

array([4, 5, 6, 7])

In [51]:
arr*2

array([2, 4, 6, 8])

In [52]:
arr**2

array([ 1,  4,  9, 16])

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100,   121,   144,   169,   196,   225,   256,   289,   324,
          361,   400,   441,   484,   529,   576,   625,   676,   729,
          784,   841,   900,   961,  1024,  1089,  1156,  1225,  1296,
         1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,  2025,
         2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,  2916,
         3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,  3969,
         4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,  5184,
         5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,  6561,
         6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,  8100,
         8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [57]:
import numpy as np 
square=np.arange(1,101).reshape(1,-1)
push=square**3
push

array([[      1,       8,      27,      64,     125,     216,     343,
            512,     729,    1000,    1331,    1728,    2197,    2744,
           3375,    4096,    4913,    5832,    6859,    8000,    9261,
          10648,   12167,   13824,   15625,   17576,   19683,   21952,
          24389,   27000,   29791,   32768,   35937,   39304,   42875,
          46656,   50653,   54872,   59319,   64000,   68921,   74088,
          79507,   85184,   91125,   97336,  103823,  110592,  117649,
         125000,  132651,  140608,  148877,  157464,  166375,  175616,
         185193,  195112,  205379,  216000,  226981,  238328,  250047,
         262144,  274625,  287496,  300763,  314432,  328509,  343000,
         357911,  373248,  389017,  405224,  421875,  438976,  456533,
         474552,  493039,  512000,  531441,  551368,  571787,  592704,
         614125,  636056,  658503,  681472,  704969,  729000,  753571,
         778688,  804357,  830584,  857375,  884736,  912673,  941192,
      

In [58]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a+a


array([2, 4, 6, 8])

In [59]:
b+b

array([10, 12, 14, 16])

In [60]:
a+b

array([ 6,  8, 10, 12])

In [62]:
a.reshape(2,2)


array([[1, 2],
       [3, 4]])